version: "3"
services:
  dbbox:
    build:
      context: ./DBBox
      dockerfile: DockerFile
    command: mysqld --sql_mode="NO_ZERO_DATE"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Eleonline,1234
      MYSQL_DATABASE: eleonline
      MYSQL_USER: eleonline
      MYSQL_PASSWORD: Eleonline,1234
    restart: always
    volumes:
      - ./data:/var/lib/mysql
  devbox:
    depends_on:
      - dbbox
    build:
      context: ./DevBox
      dockerfile: DockerFile
    ports:
      - "8000:80"
      - "4430:443"
    volumes:
      - ./eleonline:/var/www/html
